baseURL: "https://stefannio.netlify.app/"
languageCode: "en-us"
title: "Stefan Nio Portfolio"
theme: hugo-profile
enableRobotsTXT: true

params:
  title: "Stef's Portfolio"
  description: "AI Engineer passionate about solving real-world problems with technology."
  favicon: "/images/nio.jpeg"
  animate: true
  theme:
    defaultTheme: "auto"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto
    # showBrandLogo: true
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  
  # Hero Section
  hero:
    enable: true
    intro: "Hey, my name is"
    title: "Stefan."
    subtitle: "AI Engineer"
    content: "Chief AI Officer @ Interlinked Global | Delivering AI-Driven Solutions to Real-World Problems."
    image: /images/portrait.jpeg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Resume"
      url: "/files/StefanNio_AI_EngineerResume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/stefanniouwa"
        - icon: fab fa-linkedin
          url: "https://linkedin.com/in/stefan-nio"

  # About
  about: 
    enable: true
    title: "About Me"
    image: "/images/about.jpeg"
    content: |-
      Stefan is Chief AI Officer and Founding Member at Interlinked Global, where he leads R&D and product development to help ASEAN businesses adopt AI with clarity and confidence—building systems that augment human capability rather than replace it.

      With a foundation in Bachelor's of Advanced Computer Science specializing in AI, Stefan's journey continued with an Honours year of academic research at The University of Western Australia, developing multi-class seizure classification models using TensorFlow and Keras. What started as fascination with machine learning algorithms evolved into a deeper question: How do we build AI that serves people, not just processes?

      That question became [Interlinked Global](https://www.interlinkedglobal.io/).

      As CAIO, Stefan architects flagship products including ARRA (AI Readiness & Risk Assessment) and the company's organisational imaging platform—leading a technical team that translates complex AI challenges into practical, human-centered solutions. From Python-based ML systems to regional-scale AI infrastructure, his work bridges technical depth with strategic vision.

      Previously an AI Engineer Intern at [CognixAI](https://cognix.au) in Sydney, building automation tools and optimizing end-to-end Python workflows, Stefan learned that the hardest problems in AI aren't technical—they're human. This insight shaped Interlinked's DNA: helping organisations see themselves clearly and transform in ways that strengthen their people and processes.

      As a founding member, Stefan has shaped both Interlinked's technology stack and its philosophy: first principles thinking, ASEAN-focused innovation, and the conviction that clarity beats complexity every time.

      Beyond code and strategy, Stefan served as Treasurer and Executive Committee member of his university's Indonesian student society, leading a 40-member team and managing event budgets. He also worked as a barista at a local café—crafting lattes with the same precision he applies to machine learning models.
    skills:
      enable: true
      title: "Technologies Stefan has been working with recently:"
      items:
        - "Building Agents with AWS Bedrock AgentCore, Strands SDK, LangChain, and LangGraph"
        - "Knowledge Graphs with Neo4J"
        - "TensorFlow, Keras, and Scikit-learn"
        - "NextJS, ReactJS, HTML, CSS, and JS"
        - "SQL, Jupyter Notebook, and Git CLI"
        - "Python"
        - "Java and C"
        - "LaTeX and Markdown"
        - "Pandas, Matplotlib, and Seaborn"
        - "Docker and REST API"
  
  # Experience Section
  experience:
    enable: true
    items:
      - job: "Chief AI Officer & Founding Member"
        company: "Interlinked Global"
        companyUrl: "https://www.interlinked.global/"
        date: "Aug 2025 - Present"
        featuredLink:
          enable: true
          name: "View the Website"
          url: "https://www.interlinked.global/"
        content: "As Chief AI Officer and Founding Member at Interlinked Global, Stefan leads R&D and product development, architecting AI solutions that help ASEAN businesses transform with confidence. He oversees the technical strategy and engineering team behind flagship products including ARRA (AI Readiness & Risk Assessment) and the company's organisational imaging platform—systems that translate complex AI challenges into practical, human-centered solutions. Stefan has shaped both the technology stack and company philosophy from the ground up, establishing first principles engineering practices and building scalable AI infrastructure tailored to Southeast Asia's unique business landscape. His leadership bridges strategic vision with technical execution, ensuring every product reflects Interlinked's core belief: AI should augment human capability, not replace it. Under his technical direction, Interlinked Global was selected as one of 150 companies worldwide to pitch at Startup Grind's annual conference in Silicon Valley."
      
      - job: "Artificial Intelligence Engineer Intern"
        company: "CognixAI"
        companyUrl: "https://cognix.au/"
        date: "Jan 2024 - May 2025"
        featuredLink:
          enable: true
          name: "View the Website"
          url: "https://cognix.au/"
        content: "At CognixAI, Stefan works as an Artificial Intelligence Engineer Intern in Sydney, NSW, where he builds AI-powered content creation tools that streamline the process of generating and posting personalized content across multiple social media platforms. Leveraging Hugging Face models, third-party AI APIs for text, video, and audio generation, and real-time data from sources like LinkedIn, X, and Bing News, he enhances user engagement and efficiency. He has researched and prototyped adaptive AI models capable of learning client-specific writing styles, enabling fine-tuned, highly personalized content generation. Through Python workflow optimization and API integrations, Stefan has reduced processing times by 25% and improved user efficiency by 40%."
      - job: "Treasurer (Executive Team)"
        company: "INDOSS at UWA"
        companyUrl: "https://www.instagram.com/indossppiauwa/?hl=en"
        date: "Feb 2024 - Dec 2024"
        featuredLink:
          enable: true
          name: "View the Instagram"
          url: "https://www.instagram.com/indossppiauwa/?hl=en"
        content: "As Treasurer and Executive Committee member of the Indonesian Students Society (INDOSS) at UWA, Stefan led a 40-member team, managed event budgets, and oversaw transparent financial operations for a 350+ member organization. He secured over $4,000 in sponsorships, tripled cash reserves, and orchestrated large-scale events with 450+ attendees, generating record revenue. This role strengthened his leadership, financial management, and collaborative decision-making skills in a fast-paced, community-driven environment."
      - job: "Software Accounting Intern"
        company: "Bayswater Mazda"
        companyUrl: "https://www.bayswatermazda.com.au/"
        date: "Nov 2020 - Feb 2021"
        featuredLink:
          enable: true
          name: "View the Website"
          url: "https://www.bayswatermazda.com.au/"
        content: "At Bayswater Mazda, Stefan worked as a Software Accounting Intern, digitizing over 15,000 tax invoices and developing a custom software solution that streamlined the transfer of 5,000+ documents, cutting processing time by 60% and saving 10 workdays each month. He built automated Excel models with PivotTables, VLOOKUP, and VBA to improve data accuracy by 25%, while collaborating with a cross-functional team to deliver a cost-efficient document management system that reduced processing times by 40%."
      - job: "Youth Leader"
        company: "WPC FAITH"
        companyUrl: "https://wpcbc.net/"
        date: "Feb 2020 – Present"
        featuredLink:
          enable: true
          name: "View the Website"
          url: "https://wpcbc.net/"
        content: >
          As a Youth Leader at WPC Faith Church, Stefan has mentored and guided high school and university students, helping them grow in faith, leadership, and community engagement. 
          He has organized weekly gatherings, coordinated youth camps, and led worship sessions, fostering a welcoming and supportive environment for young members. 
          This role has strengthened his skills in public speaking, event coordination, and working collaboratively with a dedicated leadership team.

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Bachelor of Advanced Computer Science (Honours), Major in Artificial Intelligence"
        school:
          name: "The University of Western Australia"
          url: "https://www.uwa.edu.au/"
        date: "2021 – 2024"
        GPA: "5.75 out of 7.0"
        content: |-
          Achievements
            - Graduated in the top 8% nationally.
            - Completed Honours research on multi-class seizure classification using deep learning (WaveNet + BiLSTM) with EEG data.
          
          Relevant Courses
            - Data Structures & Algorithms, Software Engineering with Java, Systems Design and Programming, Agile Web Development.
            - Machine Learning, Deep Learning, Computational Modelling, Computer Vision, Algorithms in Agents and AI.

      - title: "High School ATAR Pathway"
        school:
          name: "Kennedy Baptist College"
          url: "https://www.kennedy.wa.edu.au/"
        date: "2017 – 2020"
        GPA: "ATAR: 95.8"
        content: |-
          Achievements
          - Graduated with an ATAR of 95.8.
          - Placed in extension (top-level) classes across Mathematics, Science, English, and Humanities, achieving the top score in Mathematics Methods.
          - Represented the school in the basketball team, contributing to interschool competitions.
          - Actively involved in leadership programs and community service initiatives.

  achievements:
    enable: true
    items:
      - title: "ACS Recognised Graduate"
        content: Recognised by the Australian Computer Society for meeting professional standards in ICT.
        url: "https://www.acs.org.au/cpd-education/accredited-courses.html"
        image: /images/acs.png

      - title: "Second Class Honours"
        content: Graduated with a Bachelor of Advanced Computer Science (Honours) with Second Class Honours, achieving GPA 5.75 and placing in the top 8% nationally.
        image: /images/honors.png
      - title: "INDOSS Professional Networking Event"
        content: Organised and hosted INDOSS’s first-ever professional networking event, connecting Indonesian students with industry professionals.
        image: /images/achievement.jpeg

  projects:
    enable: true
    items:
      - title: Honours Research Thesis — Seizure Classification (EEG)
        content: Built a WaveNet–BiLSTM pipeline in TensorFlow/Keras to classify between seven seizure types from raw EEG; explored channel-wise attention and rigorous patient-independent evaluation.
        image: /images/project1.png 
        featured:
          name: Read Dissertation (PDF)
          link: /files/Nio_Honours_Dissertation__Seizure_Classification.pdf # edit this
        badges:
          - "TensorFlow"
          - "Keras"
          - "Python"
          - "EEG"
          - "Deep Learning"
        links:
          - icon: fab fa-github
            url: https://github.com/stefanniouwa/SeizureNet
          - icon: fas fa-file-pdf
            url: /files/Nio_Honours_Dissertation__Seizure_Classification.pdf

      - title: Decision Trees & Random Forest — Hyperparameter Tuning
        content: Implemented classification on the Breast Cancer Wisconsin dataset to distinguish between benign and malignant tumors, using GridSearchCV and cross-validation to tune Decision Trees and Random Forests; improved accuracy and reliability with robust evaluation.
        image: /images/project2.png
        featured:
          name: GitHub Repo
          link: https://github.com/stefanniouwa/breastCancerDecisionTree
        badges:
          - "Python"
          - "scikit-learn"
          - "GridSearchCV"
          - "Cross-Validation"
        links:
          - icon: fab fa-github
            url: https://github.com/stefanniouwa/breastCancerDecisionTree

      - title: WeatherForecast — GRU Models & VAE for WA Temps
        content: Built GRU-based models (direct, sequential, encoder–decoder) to forecast min/max temperatures; added a VAE to synthesize realistic temperature sequences.
        image: /images/project3.png
        featured:
          name: GitHub Repo
          link: https://github.com/stefanniouwa/WeatherForecast/ 
        badges:
          - "Python"
          - "RNN/GRU"
          - "Time Series"
          - "VAE"
        links:
          - icon: fab fa-github
            url: https://github.com/stefanniouwa/WeatherForecast/
      
      - title: ProblemHub — Full-Stack Competitive Programming Hub
        content: Centralised repository for competitive programming problems in problem-tools format; full-stack app with Next.js + Tailwind (frontend) and Django + SQLite (backend), containerised with Docker for dev/prod.
        image: /images/architecture.png
        featured:
          name: GitHub Repo
          link: https://github.com/N0nameleft/Problem-Hub
        badges:
          - "Next.js"
          - "React"
          - "TailwindCSS"
          - "Django"
          - "SQLite"
          - "Docker"
          - "REST API"
        links:
          - icon: fab fa-github
            url: https://github.com/N0nameleft/Problem-Hub

  # Contact            
  contact:
    enable: true
    # title: "Custom Name"
    content: "My inbox is always open. Whether you’re tackling a tricky project, planning your next move, or just curious about my work, I’d be happy to connect."
    #btnName: Mail me
    #btnLink: mailto:gurusabarisha@gmail.com

    # Remove or ignore btnName/btnLink when using Formspree
    formspree:
      enable: true
      formId: xrblrejj  # e.g., xyzabcd
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 6


  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false

    socialNetworks:
      github: "https://github.com/stefanniouwa"
      linkedin: "https://linkedin.com/in/stefan-nio"

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: true

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
